version: "3"

services:
  app:
    image: todo
    container_name: todo
    #command: --db_host=172.17.0.1
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - appnet

  db:
      image: postgres
      restart: always
      shm_size: 128mb
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: site
        POSTGRES_PASSWORD: site
        POSTGRES_DB: site
      ports:
        - "5432:5432"
      networks:
        - appnet

volumes:
    pgdata:

networks:
  appnet:
    driver: bridge
    name: appnet