version: "3"

services:

  db:
      image: postgres
      restart: always
      # set shared memory limit when using docker-compose
      shm_size: 128mb
      # or set shared memory limit when deploy via swarm stack
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: site
        POSTGRES_PASSWORD: site
        POSTGRES_DB: site
      ports:
      - "5432:5432"
volumes:
    pgdata: